### ISSUE TITLE
Docker-compose does not open port 53

### ISSUE THREAD

**Issue by DatPenguin** [pschiffe/docker-pdns#102]
Hi,

The docker-compose file works great overall, but it does not expose the port 53/udp outside of its containers, so it is not possible to use the server without having to expose it manually. Is that the intended behavior ? The README also did not mention whether you should open it on the master or not ; doing so seems to works but it is maybe not the way you are supposed to do it.

Thanks !

**Comment by pschiffe** [comment]
Hi @DatPenguin. The docker-compose is setup that the services work within [internal virtual network `pdns`](https://github.com/pschiffe/docker-pdns/blob/master/docker-compose.yml#L121). There are 3 containers that use port `53/udp` - resolver, master and slave. It depends on you what you want to achieve - the included docker-compose file is more of an example what and how can be configured.
