### ISSUE TITLE
AXFR notify docker gateway ip address 

### ISSUE THREAD

**Issue by bohemtucsok** [pschiffe/docker-pdns#111]
Hello, my problem is the following. I created the master server and set it up. This configuration works fine.

Then I created the slave server with this configuration

(master)

version: '2.2'

services:
  mariadb:
    image: mariadb
    networks:
      pdns:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: powerdns
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    restart: always

  pdns-master:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: ns5.xxxx.com
    networks:
      pdns:
        ipv4_address: 172.6.0.20
        aliases:
          - pdns
    extra_hosts:
      - 'ns5.xxxx.com:192.168.10.50'
      - 'ns10.xxxx.com:192.168.10.100'
      - 'ns15.xxxx.com:192.168.10.150'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUBLIC_HOST=192.168.10.50
      - PDNS_gmysql_password=my-secret-pw
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=172.6.0.0/16
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=192.168.10.100,172.6.0.1,192.168.10.150
      - PDNS_also-notify=192.168.10.100
      - PDNS_enable-lua-records=yes
    depends_on:
      - mariadb
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: always

  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi
    networks:
      pdns:
        aliases:
          - pdns-admin-uwsgi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_PASSWORD='my-secret-pw'
      - PDNS_VERSION=4.7
      - PDNS_API_KEY=secret
    depends_on:
      - mariadb
      - pdns-master
    restart: always

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    networks:
      - pdns
    ports:
      - '8989:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pdns-admin-uwsgi
    restart: always

networks:
  pdns:
    ipam:
      config:
        - subnet: 172.6.0.0/16
          gateway: 172.6.0.1

volumes:
  mariadb:

The problem is imminent
When the master server sends the axfr notify, the master server docker gateway ip appears in the log on the slave server and the process does not complete

(slave)

version: '2.2'

services:
  mariadb:
    image: mariadb
    networks:
      pdns:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: powerdns
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    restart: always

  pdns-slave:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: ns15.xxxxx.com
    networks:
      pdns:
        ipv4_address: 172.6.0.21
        aliases:
          - pdns
    extra_hosts:
      - 'ns5.xxxxx.com:192.168.10.50'
      - 'ns10.xxxxx.com:192.168.10.100'
      - 'ns15.xxxxx.com:192.168.10.150'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts
    environment:
      - PDNS_gmysql_dbname=powerdns
      - PDNS_gmysql_password=my-secret-pw
      - PDNS_slave=yes
      - PDNS_superslave=yes
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=172.6.0.0/16
      - PDNS_version_string=anonymous
      - PDNS_disable_axfr=yes
      - PDNS_allow_notify_from=172.6.0.0/16,192.168.10.50
      - SUPERMASTER_IPS=192.168.10.50
      - PDNS_enable-lua-records=yes
      - PDNS_trusted-notification-proxy=172.6.0.1
    depends_on:
      - mariadb
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: always

networks:
  pdns:
    ipam:
      config:
        - subnet: 172.6.0.0/16
          gateway: 172.6.0.1

volumes:
  mariadb:

This is the message:

  Error resolving SOA or NS for xxxxx.com at: 172.6.0.1: Query to '172.6.0.1' for SOA of 'xxxxx.com' produced no answers

Does anyone have an idea what I messed up???

**Comment by pschiffe** [comment]
what's the network setup like? is it 2 different machines?
do you have `NS` records set correctly on the domain?

**Comment by bohemtucsok** [comment]
hi, yes, we are talking about two different vps servers, the ns records are set properly

**Comment by pschiffe** [comment]
powerdns may have some issues when dealing with NAT during zone transfers.. if possible, I would probably suggest to use `network: host` for pdns and thus get rid of the NAT (if you want to keep master/slave replication)
alternatively, you can use replication on mysql level, and use `NATIVE` type of zones in pdns
