### ISSUE TITLE
Versioning should follow PDNS versioning...

### ISSUE THREAD

**Issue by wargamez** [pschiffe/docker-pdns#115]
It would be great if the docker images and release tags here could follow the same versioning as PDNS e.g 4.7.4 
Ref: https://doc.powerdns.com/authoritative/changelog/

This way it would be so much easier knowing exactly which version we are on. Also any plans for an 4.8.1 image?

/E

**Comment by pschiffe** [comment]
Hi @wargamez, thanks for the suggestion. This is a little bit tricky to achieve in this case, as I'm not compiling the PDNS myself, but using the pre-compiled packages of PDNS from Fedora and Alpine. The best balance here for now is to track the minor version in the tags and ignore the patch version. The patch version is visible in the docker logs or in the output of Github action used to build the images, here in this repo.

PDNS 4.8.3 was just pushed to the docker hub under tags `latest` and `alpine`, `4.8` tag will follow soon.
