### ISSUE TITLE
Version 4.8 support ?

### ISSUE THREAD

**Issue by DatPenguin** [pschiffe/docker-pdns#117]
Hi,
Version 4.8 has been released several months ago, will your images be updated to this version?
Thanks.

**Comment by pschiffe** [comment]
I'm planning to, just waiting for the next Fedora release, should happen this week.

**Comment by pschiffe** [comment]
4.8 is now available under `latest` and `alpine` tags, `4.8` tags will be added later

**Comment by pschiffe** [comment]
version 4.8 has been tagged
