### ISSUE TITLE
update the admin UI container - development moved to a new repo

### ISSUE THREAD

**Issue by ShaunDwyer** [pschiffe/docker-pdns#12]
Hi,

I've had a play with your pdns-admin-uwsgi container.. software version you're using seems like it was a bit buggy and missing some critical features...

It seems like development has moved for the admin UI from 0x97's personal gitlab to https://github.com/ngoduykhanh/PowerDNS-Admin

Looks like its not a fork, but the same author?

Cheers!
-Shaun

**Comment by pschiffe** [comment]
Hello,

when I was creating this repo, https://github.com/ngoduykhanh/PowerDNS-Admin wasn't maintained and the 0x97 repo had couple features more than the ngoduykhanh repo. Thanks for letting me know that things have changed. I'll try to look into it and move it a bit forward again, if time allows.

peter

**Comment by ShaunDwyer** [comment]
Hi Peter,

Thanks very much.. appreciate your efforts!

I've tested the admin interface from the ngoduykhanh repo in the last couple of days, and can confirm the admin interface is pretty complete now... it works well and seems fully featured. Its looks to have better than feature parity with the old poweradmin php tool from years ago.

The way he's published it in there might make it a challenge to integrate... I've hacked something together, but im not really happy with how I've done it; its a bit too cancerous to share right now. If i come up with something a bit better before you do, i'll try to contribute it back.

Cheers!
-Shaun

**Comment by pschiffe** [comment]
Hey there, I should write you sooner, but the ngoduykhanh version of PowerDNS Admin is now available in this repo and on docker hub as `pschiffe/pdns-admin-uwsgi:ngoduykhanh` and `pschiffe/pdns-admin-static:ngoduykhanh`. Unfortunately this version is not backward compatible with the 0x97's version, so there is no direct upgrade path :(

**Comment by ShaunDwyer** [comment]
Thanks Peter.. appreciate the heads up!

Happy new year!
Cheers!
-Shaun
