### ISSUE TITLE
dns port (53)

### ISSUE THREAD

**Issue by Julien-Quidam** [pschiffe/docker-pdns#121]
Hi @pschiffe !

Thanks for your work :)

I have a question. Where I should open the dns port (53) ?
On pdns-recursor pdns-slave or pdns-master ?

**Comment by pschiffe** [comment]
Hi, depends on what you want to achieve. If you want to host a DNS zone (domain), you should have master and slave running on different servers and both should have port 53 exposed. Recursor is only for if you need some custom DNS resolver with custom configuration. You usually don't need that.
