### ISSUE TITLE
`pschiffe/pdns-admin` requires CPU with `x86_64-v2` support unlike the rest.

### ISSUE THREAD

**Issue by GamePlayer-8** [pschiffe/docker-pdns#122]
Good afternoon,

There's an issue with `docker-compose-pgsql.yml` Docker compose file, where in `pschiffe/pdns-admin` image, glibc requires a CPU with `x86_64-v2` instructions while the rest of containers can run on `x86_64-v1`.

**Comment by pschiffe** [comment]
Hello, thanks for the report. Is this happening in some virtual environment, or physical HW? Could out post output of `cat /proc/cpuinfo | grep 'model name' | head -1` command?

**Comment by pschiffe** [comment]
I see. In that case, I think the best option would be to pass the host CPU configuration to the VM. You can change this even after the VM was created, you just need to reboot it to pick up the changes:

![Screenshot from 2024-01-12 20-50-12](https://github.com/pschiffe/docker-pdns/assets/3899107/3428d9ed-a833-4d47-b60a-ad6ea01563b4)

Thanks to this you also get better performance inside of the VM. For more information why is this needed, follow this link: https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level

I understand that the images are not consistent in this requirement, but they all benefit from it if available. Moreover, most of the CPUs today should meet this requirement without a problem.
