### ISSUE TITLE
Pdns Webserver is not accepting request from outside docker

### ISSUE THREAD

**Issue by sadiqueWiseboxs** [pschiffe/docker-pdns#123]
Pdns Webserver is not accepting request from outside docker even though webserver-allow-from is given 0.0.0.0

**Comment by HerrSammyDE** [comment]
Have you set these three things?
```
- PDNS_webserver=yes
- PDNS_webserver_address=0.0.0.0
- PDNS_webserver_allow_from=0.0.0.0/0
```

**Comment by pschiffe** [comment]
@sadiqueWiseboxs please paste your `/etc/pdns/pdns.conf` config file from inside of the container and logs from the running container after you failed to connect to the webserver.
