### ISSUE TITLE
Rootless run

### ISSUE THREAD

**Issue by vipinjn24** [pschiffe/docker-pdns#130]
Hi I am trying to run the image rootless.
but the container fails with the error trying to write to config file with permission denied.

Can we not run this rootless?

If not could you please see if we can fix this behavior.

I am using this image on kubernetes.

**Comment by pschiffe** [comment]
Which image and tag exactly?

**Comment by vipinjn24** [comment]
pschiffe/pdns-mysql:alpine

**Comment by pschiffe** [comment]
Should be fixed with https://github.com/pschiffe/docker-pdns/commit/e34dcd96659b8680334a3d869ef2f251ef8cdc27

Can you try once the images are built?

**Comment by vipinjn24** [comment]
thanks will check it out

**Comment by vipinjn24** [comment]
Its not working same error permission denied, i tried user 1000 and also tried to create a new user pdns and used its id. but to no avail.
without providing the runasuser id it runs as root.

**Comment by pschiffe** [comment]
Just use `pdns` user, it's already present there.

**Comment by vipinjn24** [comment]
Let me check if kubernetes supports using name

**Comment by pschiffe** [comment]
In the alpine variant the UID is `100`.

**Comment by vipinjn24** [comment]
Okh let me try that

**Comment by vipinjn24** [comment]
The user change permitted the file write, but it seems more on the other things like ports and sockets
ports can be handled if we change them, let me check the socket too.

Feb 06 12:54:10 Unable to change group ownership of controlsocket at '/var/run/pdns/pdns.controlsocket', reason: Operation not permitted
Feb 06 12:54:10 Listening on controlsocket in '/var/run/pdns/pdns.controlsocket'
Feb 06 12:54:10 Guardian is launching an instance
Feb 06 12:54:10 Loading '/usr/lib/pdns/pdns/libgmysqlbackend.so'
Feb 06 12:54:10 This is a guarded instance of pdns
Feb 06 12:54:10 Unable to bind UDP socket to '0.0.0.0:53': Permission denied

**Comment by pschiffe** [comment]
Ports can be changed via env vars, the permissions for the socket should be fixed already in the image - are you using any volumes or something? Could you try to completely recreate the pods?

**Comment by vipinjn24** [comment]
not using the volumes, but post port change

Feb 06 13:01:38 Unable to change group ownership of controlsocket at '/var/run/pdns/pdns.controlsocket', reason: Operation not permitted
Feb 06 13:01:38 Listening on controlsocket in '/var/run/pdns/pdns.controlsocket'
Feb 06 13:01:38 Guardian is launching an instance
Feb 06 13:01:38 Loading '/usr/lib/pdns/pdns/libgmysqlbackend.so'
Feb 06 13:01:38 This is a guarded instance of pdns
Feb 06 13:01:38 UDP server bound to 0.0.0.0:3053
Feb 06 13:01:38 UDP server bound to [::]:3053
Feb 06 13:01:38 TCP server bound to 0.0.0.0:3053
Feb 06 13:01:38 TCP server bound to [::]:3053
Feb 06 13:01:38 PowerDNS Authoritative Server 4.8.3 (C) 2001-2022 PowerDNS.COM BV
Feb 06 13:01:38 Using 64-bits mode. Built using gcc 13.2.1 20231014 on Nov 15 2023 11:38:56 by buildozer@localhost.
Feb 06 13:01:38 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Feb 06 13:01:38 Unable to set effective group id to 101: Operation not permitted
Feb 06 13:01:39 Our pdns instance exited with code 1, respawning

**Comment by vipinjn24** [comment]
this is the security contex i am using.

securityContext:
        runAsUser: 100
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

**Comment by vipinjn24** [comment]
oh  got it

**Comment by vipinjn24** [comment]
removing group worked let me fix the group id

**Comment by vipinjn24** [comment]
this worked for me but can you do that for all other images including recursor and web admin

**Comment by vipinjn24** [comment]
this works for me but could you please do this for other images like recursor and admin?

**Comment by pschiffe** [comment]
Recursor is done, but admin won't work that way, there's multiple processes running under different users managed by supervisord.

**Comment by vipinjn24** [comment]
ahh my pull policy was not always, now updated, thanks
