### ISSUE TITLE
Looking for a installation guide

### ISSUE THREAD

**Issue by Graxo** [pschiffe/docker-pdns#132]
Hi have cloned the repo and used the pgsql docker-compose file to set every thing up.
I generated my own api key and needed password and also put them in the docker-compsoe file.
After running it, everything deploys but not all ports are exposed for example. Im getting kinda stuck now and dont know what else to throubleshoot.

The PowerDNS admin interface looks fine, but when creating a domain and trying to resolve it i get time outs.
I get the feeling the powerDNS admin interface is not communicating to the powerdns server.
Im looking for some sort of installation guide to help me find what i did wrong.

**Comment by Graxo** [comment]
Also and api request is empty:

```
curl -H 'X-API-Key: <API_KEY>' http://10.10.140.100:8081/api/v1/servers/localhost/zones | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
```

**Comment by pschiffe** [comment]
Hi @Graxo. The installation guide is kind of tricky, b/c it really depends on what you want to achieve here. The provided compose and playbook files are more of an examples of what and how can be done. For example, there are always primary and secondary DNS servers as well as a recursor - but these 3 services share the same ports (53), so they cannot be exposed all at once on the same host. Usually you will have these services running on different hosts for them to make sense.

If you have troubles, the logs are your best friend. Check logs of all containers - `docker logs docker-pdns_pdns-admin-pgsql_1`, `docker logs docker-pdns_pdns-pgsql-master_1`, etc to see if there are any errors. If you see any, go from there. Feel free to post errors here if you don't know how to fix them.
