### ISSUE TITLE
master slave sync issue?

### ISSUE THREAD

**Issue by hpcmtint** [pschiffe/docker-pdns#133]
Hello Peter, 

While I'm still fine-tuning my Docker Compose setup and have integrated it with phpipam, among other tools, I'm uncertain whether the slave automatically synchronizes with the master. Although I've configured everything as per your example, including importing my zone files into the master, I expected the slave to sync accordingly. However, I've attempted this without success.

```bash
[root@ns1 /]# pdns_control notify 172.22.0.21
Failed to add to the queue - see log
```

**Comment by pschiffe** [comment]
Hello, what does the log says? You can test the slave with `dig` command asking it directly. It should answer the same as the master.

**Comment by pschiffe** [comment]
Let me summarize if I understand correctly. You want to have primary and secondary DNS server (master & slave). But both will be running in the same swarm cluster, and both have access to the same database?

If that's true, I would recommend to just drop the replication, drop the `powerdnsslave` db, and let both DNS servers share the same `powerdns` db. If you have only 1 mysql server, I think that's the best option. DNS replication just complicates things unnecessarily here.
