### ISSUE TITLE
Problem with replicate of database

### ISSUE THREAD

**Issue by rflor01** [pschiffe/docker-pdns#138]
Hello, first of all thanks for you work, appreciated. 

I am having troubles because the information in the database powerdns in my master is not replicated in the database powerdnsslave in my slave, using this repo. Is there anything i should change to make it work? 

Thank you so much.

**Comment by pschiffe** [comment]
Hi @rflor01. If you are using docker-compose provided in this repo, and want to utilize the DNS replication between master/slave PDNS servers, you need to properly configure the NS records of the zone on the master server. The NS records must exist for both - the master as well the slave.

**Comment by rflor01** [comment]
Thanks, so helpful, it was also not working because i was using LUA records and i needed to configure PDNS to use them. 

Thank yo so much.
