### ISSUE TITLE
Interested in joined effort + armv32/armv64 builds

### ISSUE THREAD

**Issue by EugenMayer** [pschiffe/docker-pdns#18]
Great work here already. I started my own work first at https://github.com/eugenmayer/docker-powerdns due to the mass of really low quality docker images which i did not consider to contribute to since the distance is just to far.

You have build a really nice solutions though and i would love to contribute, if you are interested.

a) arm based builds ( arm32v6/7 for rpi1/2 and arm64v8 for pi3/bananapir and all others )
I have done this in my repo already and would just migrate those solutions to your repo

b) I got into troubles building https://github.com/ngoduykhanh/PowerDNS-Admin.git specificly using there specs
 - a very long build time ( 5 minutes ) due to all the python contribs fetched.. i did not properly use virtuenv, maybe thats the key here
 - after starting the image ( its a combined static/backend) the image takes about 3 minutes to do something ( generate assets ) and then the GUI was responding. I am not sure this is because i bundled with sqlite and it actually has issues with that or its again something which went wrong because i did not user flask/virtualenv

I would like to contribute a) and solve b) together, if those exists with your images. Splitting static and backend is a really nice work already, i hope we can stick to that, also incorporate #12 or stick with your repo of choice if that is actually the reason b) works.

I would split all those things in different issues if you are actually interested in me creating those PRs - let me know

And thanks for your work!

**Comment by pschiffe** [comment]
Hey there! Thank you very much for your willingness to contribute to this repo. All of what you have proposed makes sense to me and I'll gladly accept your contributions. However, your PR is just too big to do a meaningful review - could you please split it up logically into multiple PRs?

What is really important to me - the updates cannot break anything for existing users. I hate it when it happens to me, so let's try to avoid it as possible for users of these images.

Regarding the 0x97 vs ngoduykhanh - we can move completely to the ngoduykhanh's repo as it seems to be more active with more features. Just again, let's try to make the update for existing users easy.

Thanks again and I'm looking forward to our cooperation!

**Comment by pschiffe** [comment]
Thanks for your honest answer. I'll see what I can do :-)

**Comment by harryzcy** [comment]
Is there any updates on this? I'm interested in having a arm64 build, and I can send a PR on this.

**Comment by pschiffe** [comment]
We now have `linux/arm64` image variants available in docker hub for `pdns-mysql` and `pdns-recursor` images :tada: 

`pdns-admin` is not available as `linux/arm64` for now, as the flask asset build timeouts the job in Github CI on arm64 VM. For now I don't see another reasonable way to go around this, but the `pdns-admin` project is now "under new management" and the development seems to be active again, so maybe the situation will be improved in the near future.

**Comment by pschiffe** [comment]
There's now a `linux/arm64` version of docker image for `pdns-admin` as well. I'm considering this now done, even though it was originally also about `armv32`, but I don't think that's important right now.
