### ISSUE TITLE
Trying to kubernetize your work

### ISSUE THREAD

**Issue by tardich** [pschiffe/docker-pdns#22]
Hi,

You've done a really nice work. Thanks for that.

I'm trying to use your work to create an Helm chart to migrate PowerDNS to Kubernetes. It's almost completed, but the uwsgi image crashes after a certain amount of time. The pod logs shows:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 411, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 377, in load_app
    raise_if_not_found=False)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/opt/powerdns-admin/app/__init__.py", line 24, in <module>
    app.config.from_object('config')
  File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 170, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 547, in import_string
    __import__(import_name)
  File "/opt/powerdns-admin/config.py", line 12
    UWSGI_PORT = tcp://10.43.148.140:9494
                    ^
SyntaxError: invalid syntax

I can't actually find what it's trying to do. The 10.43.148.140 is actually the service IP that the pods's is given at start time, and I just can't find any reference of it into the files...  until the pod crashes.

Any clue?

**Comment by tardich** [comment]
> asdfasdfasdf

> ``

**Comment by pschiffe** [comment]
`config.py` file is a python file, so the correct syntax is `UWSGI_PORT = 'tcp://10.43.148.140:9494'`. Also be sure to use `pschiffe/pdns-admin-uwsgi:ngoduykhanh` version of images; the `latest` tag is an old version.

**Comment by tardich** [comment]
That's the image I'm using. In fact, here's my manifest file:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-admin-uwsgi
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pdns-admin-uwsgi
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: pdns-admin-uwsgi
    spec:
      containers:
      - image: pschiffe/pdns-admin-uwsgi:ngoduykhanh
        imagePullPolicy: IfNotPresent
        name: pdns-admin-uwsgi
        env:
        - name: PDNS_ADMIN_SQLA_DB_HOST
          value: "'mariadb'"
        - name: PDNS_ADMIN_SQLA_DB_PORT
          value: "'3306'"
        - name: PDNS_ADMIN_SQLA_DB_USER
          value: "'root'"
        - name: PDNS_ADMIN_SQLA_DB_PASSWORD
          value: "'********'"
        - name: PDNS_ADMIN_SQLA_DB_NAME
          value: "'powerdnsadmin'"
        - name: PDNS_API_URL
          value: "http://powerdns-master:8081/"
        - name: PDNS_API_KEY
          value: "p0w3rdns!"
        - name: PDNS_VERSION
          value: ""
        ports:
        - containerPort: 9494
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/powerdns-admin/upload
          name: user-uploads
          readOnly: false
      restartPolicy: Always
      volumes:
      - name: user-uploads
        persistentVolumeClaim:
          claimName: pdns-admin-uwsgi

The started pod is getting it's IP from the kubernetes environment's pod name (pdns-admin-uwsgi.

Where is that string (UWSGI_PORT) set, exactly?  I didn't find the offending string anywhere to validate anything...

**Comment by pschiffe** [comment]
The template of that file is here: https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-base-ngoduykhanh/config.py.tpl

And the content is filled in in entrypoint here: https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-uwsgi-ngoduykhanh/docker-entrypoint.sh#L28

**Comment by tardich** [comment]
Checked everywhere in all the files that compose the helm chart for it, and I don't have this variable set either. Did a grep -Ri for it, and didn't find any. I'll try to set this variable to nothing at all.

I specifically set the variable in my deployment as empty, and the error disappeared. But then, another one came in, with the same kind of error:

File "/opt/powerdns-admin/config.py", line 13
    UWSGI_PORT_9494_TCP = tcp://10.43.181.109:9494

In fact, I have all these variables set in the running pod at startup:

PDNS_ADMIN_LOG_LEVEL='INFO'
PDNS_ADMIN_UWSGI_PORT_9494_TCP_ADDR=10.43.130.183
PDNS_API_KEY=*********
PDNS_ADMIN_SAML_ENABLED=False
PDNS_ADMIN_UWSGI_SERVICE_PORT=9494
PDNS_ADMIN_UWSGI_PORT_9494_TCP_PROTO=tcp
PDNS_API_URL=http://powerdns-master:8081/
PDNS_ADMIN_UWSGI_PORT=''
PDNS_ADMIN_SQLA_DB_NAME='powerdnsadmin'
PDNS_ADMIN_UWSGI_PORT_9494_TCP_PORT=9494
PDNS_ADMIN_UWSGI_PORT_9494_TCP=tcp://10.43.130.183:9494
PDNS_ADMIN_SQLA_DB_HOST='mariadb'
PDNS_ADMIN_UWSGI_SERVICE_HOST=10.43.130.183
PDNS_ADMIN_SQLA_DB_USER='root'
PDNS_ADMIN_SQLA_DB_PORT='3306'
PDNS_ADMIN_SQLA_DB_PASSWORD='*************'
PDNS_VERSION=

(note the PDNS_ADMIN_UWSGI_PORT I set to '')

Where all these variables get created, I don't have a clue for now. Will try to investigate. But it may seem a bad idea to take into account all these variable names, as any misdeclared variables could interfere with the normal behavior of the container.

**Comment by tardich** [comment]
Looking deeper in the environment variables list of the uwsgi container, it appears that kubernetes create a whole lot of environment variables that are defined based on pod names, namespace names, service names and ports. Probably very useful in a lot of cases, but not handy at all in this particular case.  :-/

**Comment by tardich** [comment]
Sorted out most of the stuff. One last thing, as it seem. In the GUI, if I click, for example, on the PDNS tab, on the right, uwsgi logs tell me that I can't conect through the API:

[2019-06-04 04:38:03,704] [ERROR] | Can not get server configuration. DETAIL: HTTPConnectionPool(host='powerdns-master-api', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe36db84438>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2019-06-04 04:38:03,712] [ERROR] | Can not get server statistics. DETAIL: HTTPConnectionPool(host='powerdns-master-api', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/statistics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe36db1fb70>: Failed to establish a new connection: [Errno 111] Connection refused'))

powerdns-master-api is the api pod internal name, which seem to be OK (tested with the FQDN, or the svc ip and they all work with Err111. Something else (like 1.1.1.1) would give me Name or service not known). So it seem I'm connecting, but getting a connection refused afterward.

Any idea of the relevant setting?

**Comment by pschiffe** [comment]
Try to reconfigure the pdns connection settings in GUI: Settings -> PDNS and check if that helps.

**Comment by chtardif** [comment]
Tried it yesterday and nope, didn't help.

**Comment by pschiffe** [comment]
Do you have PDNS server API working? You need to have the following settings configured:
```api=yes
api-key=secret
webserver=yes
webserver-address=0.0.0.0
webserver-allow-from=172.5.0.0/16```

**Comment by pschiffe** [comment]
There is now an example kubernetes configuration in the repo: https://github.com/pschiffe/docker-pdns/tree/master/examples/kubernetes
