### ISSUE TITLE
nginx.conf host not configurable

### ISSUE THREAD

**Issue by MartinVerges** [pschiffe/docker-pdns#27]
As I use different hostnames, the following line causes some trouble. 
https://github.com/pschiffe/docker-pdns/blob/c7510e5a2eddd07482444765aa9ba26ab84a7ba5/pdns-admin-static-ngoduykhanh/pdns-nginx.conf#L48 

It would be nice if you could add an environment variable to configure it

**Comment by pschiffe** [comment]
After 4 years in the making, this is now possible with `PDNS_ADMIN_STATIC_UWSGI_HOST` and `PDNS_ADMIN_STATIC_UWSGI_PORT` env vars.
