### ISSUE TITLE
pdns-admin-uwsgi issue with nginx reverse proxy

### ISSUE THREAD

**Issue by boarder981** [pschiffe/docker-pdns#3]
Hi again!

When using the `pdns-admin-uwsgi` and `pdns-admin-static` containers, linking them as instructed in the README, it works perfectly.  I can access the app at http://dockerhost.mycompany.com:8999 and all seems fine.

However, I already have a separate docker host running nginx proxy containers, and I'd like to use this instead of the `pdns-admin-static` container.  I am publishing a port on the `pdns-admin-uwsgi` container as such:

```
docker run -dt -p 9494:9494 --name pdns-admin-uwsgi \
  --privileged \
  -v pdns-admin-upload:/opt/powerdns-admin/upload \
  -e PDNS_ADMIN_SQLA_DB_HOST="'10.x.x.x'" \
  -e PDNS_ADMIN_SQLA_DB_PORT="'3306'" \
  -e PDNS_ADMIN_SQLA_DB_USER="'pdnsdbuser'" \
  -e PDNS_ADMIN_SQLA_DB_PASSWORD="'mysqlsupersecret'" \
  -e PDNS_ADMIN_SQLA_DB_NAME="'pdnsadmin'" \
  -e PDNS_ADMIN_PDNS_STATS_URL="'http://10.x.x.x:8081/'" \
  -e PDNS_ADMIN_PDNS_API_KEY="'somelongkey'" \
  -e PDNS_ADMIN_PDNS_VERSION="'4.0.0'" \
  -e PDNS_ADMIN_LDAP_TYPE="'ldap'" \
  -e PDNS_ADMIN_LDAP_URI="'ldaps://ldap.mycompany.com:636'" \
  -e PDNS_ADMIN_LDAP_USERNAME="'uid=pdnsuser@mycompany.com,ou=people,dc=mycompany,dc=com'" \
  -e PDNS_ADMIN_LDAP_PASSWORD="'ldapsecretpass'" \
  -e PDNS_ADMIN_LDAP_SEARCH_BASE="'ou=People,dc=mycompany,dc=com'" \
  -e PDNS_ADMIN_LDAP_USERNAMEFIELD="'uid'" \
  -e PDNS_ADMIN_LDAP_FILTER="'(accessRole=uniqueIdentifier=pdnsadmin,ou=roles)'" \
  pschiffe/pdns-admin-uwsgi
```

The location blocks of my nginx conf looks like this:

```
location /static/ {
  alias /opt/powerdns-admin/app/static/;
}

location / {
  try_files $uri @pdns_admin;
}

location @pdns_admin {

  include            uwsgi_params;
  uwsgi_pass         backend;

  uwsgi_param        Host $http_host;
  uwsgi_param        X-Real-IP $remote_addr;
  uwsgi_param        X-Forwarded-For $proxy_add_x_forwarded_for;
  uwsgi_param        X-Forwarded-Proto $scheme;
}
```

When I hit the proxy through my browser, it does return data and I can login, see zones, etc... but the HTML is ugly and isn't formatted.  I see things like this in the nginx logs:

```
10.29.23.25 - - [11/Oct/2017:16:46:17 +0000] "GET /static/custom/js/select2.min.js HTTP/1.1" 404 571 "https://dockerproxy.mycompany.com:32000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" "-"
2017/10/11 16:46:17 [error] 16#16: *2 open() "/opt/powerdns-admin/app/static/custom/js/select2.min.js" failed (2: No such file or directory), client: 10.x.x.x, server: *.mycompany.com, request: "GET /static/custom/js/select2.min.js HTTP/1.1", host: "dockerproxy.mycompany.com:32000", referrer: "https://dockerproxy.mycompany.com:32000/"
```

I shelled into the `pdns-admin-uwsgi` container and cd'd to `/opt/powerdns-admin/app`... sure enough, the entire `static` directory is missing!  I do see the directory [here](https://git.omicroninteractive.com/0x97/powerdns-admin/tree/master/app)

I'm confused as to how this works via the static container, but not my proxy.  Any ideas as to how I can get this working?

**Comment by pschiffe** [comment]
All static files are in the `pdns-admin-static` container. If you want your proxy, you need to put it in front of the `pdns-admin-static` container. See https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-static/pdns-nginx.conf#L5 and https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-static/Dockerfile#L6

**Comment by boarder981** [comment]
I was just trying to simplify the equation by having 2 containers, rather than 3.  I see what you're saying though, essentially the static container is acting as the web server for the uwsgi app.

I'm not very well versed in nginx.  If I remove [this](https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-uwsgi/Dockerfile#L18) and build the image, would I be able to use my proxy to serve the requests?  I'm reading up a bit on passing headers with the uwsgi_param options in nginx, but wondering if you have any experience with this...

**Comment by pschiffe** [comment]
Here you go: https://github.com/pschiffe/docker-pdns/commit/9383a1f2871e4ad586a638a5328a7578db32b07f
You can try it now without the `pdns-admin-static` container (wait until images on Docker hub are rebuilt), but it's not recommended, you may encounter some issues. Let me know how it goes.

**Comment by boarder981** [comment]
Thank you!  I spent some time on this, but was unable to get it working.  I need to read up a bit more on nginx configuration.

In any case, for now I am using a combination of the `pdns-admin-uwsgi` and `pdns-admin-static` containers.  Working well so far.

Once again, I appreciate all your help :)

**Comment by pschiffe** [comment]
Sure, no problem. Feel free to open an issue in case of more problems :-)
