### ISSUE TITLE
Supermaster not work (Unable to find backend)

### ISSUE THREAD

**Issue by dacrhu** [pschiffe/docker-pdns#30]
Hi, can you help me?

Supermaster not working:

> Mar 06 08:46:41 Received NOTIFY for test.local from xxx.xxx.xxx.xxx:19711 for which we are not authoritative, trying supermaster
> Mar 06 08:46:41 Unable to find backend willing to host test.local for potential supermaster 94.130.189.144. Remote nameservers: 
> Mar 06 08:46:41 ns2.test.local
> Mar 06 08:46:41 ns1.test.local

```
ns2	A	Active	3600	yyy.yyy.yyy.yyy			
ns1	A	Active	3600	xxx.xxx.xxx.xxx			
@	NS	Active	3600	ns2.test.local.			
@	NS	Active	3600	ns1.test.local.			
@	SOA	Active	1800	ns1.test.local. hostmaster.test.local. 2020030206 10800 3600 604800 3600
```

Thank you!
David

**Comment by theel0ja** [comment]
Can you send your configuration?

**Comment by dacrhu** [comment]
Of course.
```
MASTER:
      - PDNS_master=yes
      - PDNS_slave=no
      - PDNS_gmysql_host=pdns-mariadb
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=root
      - PDNS_gmysql_password=****
      - PDNS_gmysql_dbname=powerdns
      - PDNS_api=yes
      - PDNS_api-key=****
      - PDNS_webserver=yes
      - PDNS_webserver-address=0.0.0.0
      - PDNS_webserver-port=8080
      - PDNS_webserver-password=****
      - PDNS_webserver-allow-from=0.0.0.0/0
      - PDNS_version-string=anonymous
      - PDNS_default-soa-name=ns1.test.local
      - PDNS_default-soa-mail=hostmaster.test.local
      - PDNS_default-ttl=1800
      - PDNS_disable-axfr=no
      - PDNS_allow-axfr-ips=yyy.yyy.yyy.yyy
      - PDNS_only_notify=yyy.yyy.yyy.yyy
      - PDNS_also-notify=yyy.yyy.yyy.yyy
```
```
SLAVE:
      - PDNS_master=no
      - PDNS_slave=yes
      - PDNS_gmysql_host=pdns-mariadb
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=root
      - PDNS_gmysql_password=****
      - PDNS_gmysql_dbname=powerdns
      - PDNS_api=no
      - PDNS_api-key=****
      - PDNS_webserver=no
      - PDNS_webserver-address=0.0.0.0
      - PDNS_webserver-port=8080
      - PDNS_webserver-password=****
      - PDNS_webserver-allow-from=0.0.0.0/0
      - PDNS_version-string=anonymous
      - PDNS_default-soa-name=ns1.test.local
      - PDNS_default-soa-mail=hostmaster.test.local
      - PDNS_default-ttl=1800
      - PDNS_disable-axfr=yes
      - PDNS_allow-notify-from=xxx.xxx.xxx.xxx
      - PDNS_superslave=yes
      - SUPERMASTER_IPS=xxx.xxx.xxx.xxx
```

**Comment by pschiffe** [comment]
Hey @dacrhu ,

this is just a control question, both dns servers seem to have the same mysql config - are they sharing the same db? master and slave need to have separate dbs.

Another thing - are hostnames configured correctly? Is master `ns1.test.local` and slave `ns2.test.local` when you call `hostname`?

Can you show content of `supermasters` table from the slave's db?

**Comment by dacrhu** [comment]
Hi @pschiffe,

- yes, they have separated db (master and slave are not the same server).
- hostnames are correct

Supermasters table in slave:

MariaDB [powerdns]> select * from supermasters
    -> ;
+----------------+--------------+---------+
| ip             | nameserver   | account |
+----------------+--------------+---------+
| xxx.xxx.xxx.xxx | 0838b1cb1140 | admin   |
+----------------+--------------+---------+
1 row in set (0.001 sec)

xxx.xxx.xxx.xxx is master IP.

Thank you!
David

**Comment by pschiffe** [comment]
So there's the issue. The second field in that row (`nameserver`) needs to be the fqdn of slave, in your case it needs to be the `ns2.test.local`, not the `0838b1cb1140`. That value comes from `hostname -f` command, see here https://github.com/pschiffe/docker-pdns/blob/master/pdns/docker-entrypoint.sh#L41

**Comment by dacrhu** [comment]
I've fixed hostname but superslave not OK yet.

root@ns1:/opt/pdnsext# docker exec -it pdns hostname -f
ns1.test.local

root@ns2:/opt/pdns# docker exec -it pdns hostname -f
ns2.test.local


MariaDB [powerdns]> select * from supermasters;
+----------------+----------------+---------+
| ip             | nameserver     | account |
+----------------+----------------+---------+
| xxx.xxx.xxx.xxx | ns2.test.local | admin   |
+----------------+----------------+---------+

Mar 06 15:50:27 Received NOTIFY for test.local from xxx.xxx.xxx.xxx:15839 for which we are not authoritative, trying supermaster
Mar 06 15:50:28 Unable to find backend willing to host test.local for potential supermaster 94.130.189.144. Remote nameservers: 
Mar 06 15:50:28 ns1.test.local

**Comment by dacrhu** [comment]
I've fixed hostname but superslave not OK yet.

root@ns1:/opt/pdnsext# docker exec -it pdns hostname -f
ns1.test.local

root@ns2:/opt/pdns# docker exec -it pdns hostname -f
ns2.test.local

MariaDB [powerdns]> select * from supermasters;
+----------------+----------------+---------+
| ip | nameserver | account |
+----------------+----------------+---------+
| xxx.xxx.xxx.xxx | ns2.test.local | admin |
+----------------+----------------+---------+

Mar 06 15:50:27 Received NOTIFY for test.local from xxx.xxx.xxx.xxx:15839 for which we are not authoritative, trying supermaster
Mar 06 15:50:28 Unable to find backend willing to host test.local for potential supermaster xxx.xxx.xxx.xxx. Remote nameservers:
Mar 06 15:50:28 ns1.test.local

**Comment by pschiffe** [comment]
OK, great. Another thing, which is tricky in this case - is slave able to resolve the master's ip? Can you `ping ns1.test.local` from the slave?

**Comment by dacrhu** [comment]
Yes, I can. This is a very mystical mistake :)

**Comment by pschiffe** [comment]
Yeah, DNS loves to be mystical :D

Please also check that the master can properly resolve the slave's ip with ping or smth.

Also you mentioned that those are 2 different machines. Are the containers able to reach each other's TCP and UDP port 53? Isn't firewall in place?

**Comment by dacrhu** [comment]
Yeah, I've added records of ns2 in to master and supermaster mode working fine :)
Thank you!
