### ISSUE TITLE
How do I use PowerDNS setuped in docker container to resolve names in my external network in which belong my host.

### ISSUE THREAD

**Issue by Abdazz** [pschiffe/docker-pdns#31]
Hello !

PowerDNS works fine on my docker host, but I can't use it in my external network in which belongs Docker host.

Help please ?

**Comment by pschiffe** [comment]
Hello, I'm not sure if I understand correctly, but you probably need to expose port 53 for TCP and UDP of pdns container, so it's reachable by other computers.

**Comment by Abdazz** [comment]
It is exactly that I want ! How can I do it  in **ansible-playbook.ym**l ?

**Comment by pschiffe** [comment]
Add this to the pdns container:
```
        published_ports:
          - "53:53"
          - "53:53/udp"
```

More info here: https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#parameter-published_ports
