### ISSUE TITLE
Communication from recursor to pdns-master not working

### ISSUE THREAD

**Issue by chris2016** [pschiffe/docker-pdns#33]
I am trying to get PDNS-Master, slave and a recursor. I have a problem connecting from recursor to the PDNS-Master. If I have the recursor running on the host itself it is working fine. 
I have to admit that my docker skills are still in alpha stage but continuously improving. All containers are starting just fine. I just don't get how to get the connection from pdns-recursor to pdns-master.

```
6390ab2e3a87        pschiffe/pdns-recursor   "/docker-entrypoint.…"   4 minutes ago       Up 4 minutes        0.0.0.0:53->53/tcp, 0.0.0.0:53->53/udp                                               pdns_pdns-recursor_1
07dea80ce338        pschiffe/pdns-mysql      "/docker-entrypoint.…"   11 minutes ago      Up 4 minutes        0.0.0.0:8081->8081/tcp, 0.0.0.0:5300->53/tcp, 0.0.0.0:5300->53/udp                   pdns_pdns-master_1
269ae7008c81        mariadb:latest           "docker-entrypoint.s…"   11 minutes ago      Up 4 minutes        3306/tcp                                                                             pdns_db_1
```

Usually containers communicate to each other via links like 

links:
  - pdns-master

but here in this case when I try to pass the config to recursor:

Recursor env:
```
      PDNS_dnssec: 'process-no-validate'
      PDNS_forward_zones: 'test.mydomain.com=pdns-master'
      PDNS_forward_zones_recurse: '.=8.8.8.8;8.8.4.4'
```

Log Output:
```
May 23 16:05:00 Redirecting queries for zone 'test.mydomain.com' to: Exception: Unable to convert presentation address 'pdns-master'
```

When I use the docker host IP address to connect to  pdns-master I get a timeout
Recursor env:
```
      PDNS_dnssec: 'process-no-validate'
      PDNS_forward_zones: 'test.mydomain.com=10.222.125.126:5300'
      PDNS_forward_zones_recurse: '.=8.8.8.8;8.8.4.4'
```

Recursor log

```
 May 23 16:10:40 Redirecting queries for zone 'test.mydomain.com' to: 10.222.125.126:5300
```
But DNS lookup results into a timeout via recursor. When i do a lookup from the docker host machine to 10.222.125.126:5300 directly it works fine. So i went into the container and have realized that in pdns-recursor i am able to telnet 10.222.125.126:5300 but telnet drops after a couple of seconds.

When I use the IP address of the container pdns-master directly it works just fine. Looking at your ansible playbook you assign static IPs to your container. Is that necessary in order to get it work?

Any help is appreciated. Although I might have not a 100% clear understanding why my setup doesnt work.

I hope you can help. 

Thanks
Chris

*** EDIT ***

I just tried the first IP of the created network in this case it was 172.21.0.1 with exposed port 5300

Recursor env:
```
      PDNS_dnssec: 'process-no-validate'
      PDNS_forward_zones: 'test.mydomain.com=172.21.0.1:5300'
      PDNS_forward_zones_recurse: '.=8.8.8.8;8.8.4.4'
```

or 

DIrect container recursor env:
```
      PDNS_dnssec: 'process-no-validate'
      PDNS_forward_zones: 'test.mydomain.com=172.21.0.3:53'
      PDNS_forward_zones_recurse: '.=8.8.8.8;8.8.4.4'
```

Both scenarios work. Is there a better way to solve this without adding static api addresses and only with the use of links?

**Comment by pschiffe** [comment]
Hi Chris,

looking at the PDNS Recursor docs, I see that `forward-zones` consists of `‘zonename=IP’ pairs, comma separated`: https://docs.powerdns.com/recursor/settings.html#forward-zones
So you have to use an IP address b/c of the PDNS.

If you want to use the external IP of the host, from inside of the Docker network, you may need to enable IP masquerade in your firewall - depending on your setup and/or open the port in fw. If the two containers would be on separate hosts - this shouldn't be an issue.

In a case, when both containers are on the same host, using the Docker internal IPs is probably the best option. And since you have to use the IP, using static IPs is probably the only option.

peter

**Comment by chris2016** [comment]
Hi,

ok thats exactly how I solved it now. Thank you for clarification.
No issue here. Closed.
