### ISSUE TITLE
Problem with "Global Search" on web-interface

### ISSUE THREAD

**Issue by JulioFranke** [pschiffe/docker-pdns#40]
Hi, how are u? :)

I have an problem with the feature "global search", where doesn't list the domains/records via api.

follow the logs of the problem:

HTTP ISE for "/api/v1/servers/localhost/search-data": Exception: GSQLBackend unable to execute query: Could not get next result from mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE name LIKE ? OR content LIKE ? LIMIT ?: Commands out of sync; you can't run this command now

if i use the follow command: 

curl -H 'X-API-Key: XXXXXX' http://X.X.X.X:8081/api/v1/servers/localhost/zones

this return all zones ihave records in my database.

My enviroment is:
(docker enviroment) 

pdns-admin-static front
pdns-admin-uwsgi back
Mariadb version: Ver 15.1 Distrib 10.3.18-MariaDB
Powerdns-server: 4.1.6 - debian buster

Do u can help me? 

Regards

**Comment by pschiffe** [comment]
Hey, I'm good, thanks :-)

do you have `PDNS_VERSION` env var set for `pdns-admin-uwsgi` container to `4.1.6`?

does the [/search-data](https://doc.powerdns.com/authoritative/http-api/search.html) endpoint work for you when you try it with curl?

peter

**Comment by JulioFranke** [comment]
> Hey, I'm good, thanks :-)
> 
> do you have `PDNS_VERSION` env var set for `pdns-admin-uwsgi` container to `4.1.6`?
> 
> does the [/search-data](https://doc.powerdns.com/authoritative/http-api/search.html) endpoint work for you when you try it with curl?
> 
> peter

yeah!! 

I set PDNS_VERSION="4.1.6". 

When i tried with curl:

curl -H 'X-API-Key: XXXXXX' http://X.X.X.X:8081/api/v1/servers/localhost/search-data
{"error": "Query q can't be blank"}

**Comment by pschiffe** [comment]
Try with the `q` param, to check if it works properly:

curl -H 'X-API-Key: XXXXXX' http://X.X.X.X:8081/api/v1/servers/localhost/search-data?q=domain

**Comment by JulioFranke** [comment]
show this error now: Internal Server Error

**Comment by pschiffe** [comment]
Yeah, so that will be probably the issue, on your pdns server. I cannot help with that :(
