### ISSUE TITLE
Login Auth

### ISSUE THREAD

**Issue by gruppferi** [pschiffe/docker-pdns#43]
Is it possible to set in docker file as Env the options for any the Auth mechanism?
PDNS UI offers LDAP,AD, O-auth...
there are some variables such as following that you can set to connect your LDAP with PDNS. can we pass these parms as ENV?
PDNS_API_URL
PDNS_API_KEY
PDNS_VERSION
LOCAL_DB_ENABLED
SIGNUP_ENABLED
LDAP_ENABLED
LDAP_TYPE
LDAP_URI
LDAP_BASE_DN
LDAP_ADMIN_USERNAME
LDAP_ADMIN_PASSWORD
LDAP_FILTER_BASIC
LDAP_FILTER_USERNAME
LDAP_SG_ENABLED
LDAP_ADMIN_GROUP
LDAP_OPERATOR_GROUP
LDAP_USER_GROUP
LDAP_DOMAIN
GITHUB_OAUTH_ENABLED
GITHUB_OAUTH_KEY
GITHUB_OAUTH_SECRET
GITHUB_OAUTH_SCOPE
GITHUB_OAUTH_API_URL
GITHUB_OAUTH_TOKEN_URL
GITHUB_OAUTH_AUTHORIZE_URL
GOOGLE_OAUTH_ENABLED
GOOGLE_OAUTH_CLIENT_ID
GOOGLE_OAUTH_CLIENT_SECRET
GOOGLE_TOKEN_URL
GOOGLE_OAUTH_SCOPE
GOOGLE_AUTHORIZE_URL
GOOGLE_BASE_URL
OIDC_OAUTH_ENABLED
OIDC_OAUTH_KEY
OIDC_OAUTH_SECRET
OIDC_OAUTH_SCOPE
OIDC_OAUTH_API_URL
OIDC_OAUTH_TOKEN_URL

**Comment by pschiffe** [comment]
Yes, it should be possible. Documented at readme with example:

> Similar to the pdns-mysql, pdns-admin is also completely configurable via env vars. Prefix in this case is PDNS_ADMIN_, but there is one caveat: as the config file is a python source file, every string value must be quoted, as shown above. Double quotes are consumed by Bash, so the single quotes stay for Python. (Port number in this case is treated as string, because later on it's concatenated with hostname, user, etc in the db uri). Configuration from these env vars will be written to the /opt/powerdns-admin/config.py file.

```
PDNS_ADMIN_SQLA_DB_HOST="'mysql'"
PDNS_ADMIN_SQLA_DB_PORT="'3306'"
PDNS_ADMIN_SQLA_DB_USER="'root'"
PDNS_ADMIN_SQLA_DB_PASSWORD="'powerdnsadmin'"
PDNS_ADMIN_SQLA_DB_NAME="'powerdnsadmin'"
```

Source where it's done: https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-base-ngoduykhanh/config.py.tpl#L12

Don't forget to use `pschiffe/pdns-admin-uwsgi:ngoduykhanh` and `pschiffe/pdns-admin-static:ngoduykhanh` image versions.
