### ISSUE TITLE
/docker-entrypoint.sh: line 32: PDNS_gmysql_socket: unbound variable

### ISSUE THREAD

**Issue by replicants** [pschiffe/docker-pdns#45]
Just started getting /docker-entrypoint.sh: line 32: PDNS_gmysql_socket: unbound variable errors after an image auto-update

I've not defined PDNS_gmysql_socket under environment in my docker-compose.yaml

Was working fine with just remote host, port, user, password, and dbname defined before todays update

**Comment by pschiffe** [comment]
ah, sorry and thank you, I've just pushed a fix.

**Comment by replicants** [comment]
thanks for the quick fix - all good and working now!
