### ISSUE TITLE
Fatal Error: Unable to acquire TCP socket: Address family not supported by protocol

### ISSUE THREAD

**Issue by rzewus** [pschiffe/docker-pdns#46]
pdns-master seems to be in crashloop when i have disabled IPv6 on the host. I can't get it working for some time :/ any help would be appreciated. 

Oct 18 11:20:16 Guardian is launching an instance
Oct 18 11:20:16 Loading '/usr/lib64/pdns/libgmysqlbackend.so'
Oct 18 11:20:16 This is a guarded instance of pdns
Oct 18 11:20:16 UDP server bound to 0.0.0.0:53
Oct 18 11:20:16 Binding [::]:53: Address Family is not supported - skipping bind
Oct 18 11:20:16 TCP server bound to 0.0.0.0:53
Oct 18 11:20:16 Fatal error: Unable to acquire TCP socket: Address family not supported by protocol
Oct 18 11:20:17 Our pdns instance exited with code 1, respawning

**Comment by pschiffe** [comment]
Hello, try to disable ipv6 also in pdns: `PDNS_local_address=0.0.0.0`
https://doc.powerdns.com/authoritative/settings.html#local-address
