### ISSUE TITLE
 Fatal error: Trying to set unknown parameter 'default-soa-mail'

### ISSUE THREAD

**Issue by rpelletierrefocus** [pschiffe/docker-pdns#50]
I am using the ansible playbook as is and I am getting this error in the pdns container. I can deleted the images and comment it out, but I am not sure what overall effect that might have.

**Comment by rpelletierrefocus** [comment]
It does turn out this is deprecated as of 4.2, as well as default-soa-name.

**Comment by pschiffe** [comment]
Thanks for the report!
