### ISSUE TITLE
Empty Response from API

### ISSUE THREAD

**Issue by swartjie** [pschiffe/docker-pdns#53]
Hey Guys,

I spun up the mysql/power dns server on our system to test, and it's running perfectly.
The only issue I'm having is that any api call to it, is getting an empty response error...

The variables:
powerdns:
        image: pschiffe/pdns-mysql
        ports:
            - 53:53
            - 8001:8001
        environment:
            - PDNS_master=yes
            - PDNS_api=yes
            - PDNS_api_key=SecurePassword
            - PDNS_webserver=yes
            - PDNS_webserver_address=10.0.0.231
            - PDNS_webserver_password=SecurePassword
            - PDNS_version_string=anonymous
            - PDNS_default_ttl=1500
            - PDNS_gmysql_host=db
            - PDNS_gmysql_port=3306
            - PDNS_gmysql_user=root
            - PDNS_gmysql_password=SecurePassword
            - PDNS_gmysql_dbname=powerdns

The API error when calling it:
cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://node1:8001/api/v1/servers/localhost/zones

any advise as to what may be wrong?

**Comment by pschiffe** [comment]
Probably not helpful anymore, but in case you still have this issue - did you provide the api password when using curl?
https://stackoverflow.com/questions/42264248/inserting-a-records-using-the-powerdns-rest-api
