### ISSUE TITLE
4.6 support?

### ISSUE THREAD

**Issue by Sispheor** [pschiffe/docker-pdns#69]
Hi there,

Is there any plan to support 4.6?
It's in package mirrors yet and it' the default version when installing on top of Rocky Linux for example.

Thanks !

**Comment by pschiffe** [comment]
hi @Sispheor, Fedora based image is already on 4.6, so I've just pushed a new tag:
https://hub.docker.com/layers/pdns-mysql/pschiffe/pdns-mysql/4.6/images/sha256-cb056810e3a7f046f527b48b14ad4c8d7b9c9501a89a70107e237cae96f34969?context=explore

Alpine version will be ready later, probably with next Alpine release.
