### ISSUE TITLE
replace envtpl with something better

### ISSUE THREAD

**Issue by pschiffe** [pschiffe/docker-pdns#71]
envtpl project is most likely dead, with last commit in 2018 - https://github.com/andreasjansson/envtpl
it's also not compatible with the latest jinja2, which makes maintaining little bit harder

ideal replacement would probably be something statically linked, maybe go based, with minimum deps

possible alternatives (must support input from shell env vars):
https://github.com/subfuzion/envtpl
https://github.com/tsg/gotpl

**Comment by spijet** [comment]
I personally use [belitre/gotpl](https://github.com/belitre/gotpl), which itself is a fork of [tsg/gotpl](https://github.com/tsg/gotpl) with some functions ported over from Helm. Unfortunately, it doesn't take any variables from the environment (only from "values" files and `-s` cmdline flag), but there's another fork that does support environment variables: [CartoDB/gotpl@0a78f0](https://github.com/CartoDB/gotpl/commit/0a78f04a4df88a03c2dde056659a766d4055baff).

**Comment by pschiffe** [comment]
This is now implemented. In the end I went with https://github.com/kha7iq/subvars
