### ISSUE TITLE
thread died with error: virtual void GSQLBackend [...] Unknown column 'd.options' in 'field list'

### ISSUE THREAD

**Issue by CptMinato** [pschiffe/docker-pdns#97]
Hi, I updated the image today and also updated the mariadb version, basically adjusted it to your [docker-compose.yml](../blob/master/docker-compose.yml) file. Unfortunately the master pdns container runs into an error: 

``Exiting because communicator thread died with error: virtual void GSQLBackend::getUpdatedMasters(std::vector<DomainInfo>&, std::unordered_set<DNSName>&, CatalogHashMap&) unable to retrieve list of master domains: Could not prepare statement: select d.id, d.name, d.type, d.notified_serial,d.options, d.catalog,r.content from records r join domains d on r.domain_id=d.id and r.name=d.name where r.type='SOA' and r.disabled=0 and d.type in ('MASTER', 'PRODUCER'): Unknown column 'd.options' in 'field list'``

I don't fully understand the issue. I can see that in the table domains, the master column is empty:

```
mysql> select * from domains;
+----+--------------------------+--------+------------+--------+-----------------+----------------+
| id | name                     | master | last_check | type   | notified_serial | account        |
+----+--------------------------+--------+------------+--------+-----------------+----------------+
|  6 |  domain.tld              |        |       NULL | MASTER |      2023011502 |      username  |
|  7 | ip.in-addr.arpa          |        |       NULL | MASTER |      2022101202 |                |
+----+--------------------------+--------+------------+--------+-----------------+----------------+
7 rows in set (0.00 sec)
```

But I don't know if that's intended or not.

Do you have any idea what the issue might be and be able to help me out?

*PS: Thank you for your work on this repo and all of the other projects you run.*

**Comment by CptMinato** [comment]
I was able to fix it.

---
I found in [these](https://doc.powerdns.com/authoritative/upgrading.html) upgrade notes:
> ### Schema changes
> The new Catalog Zones feature comes with a mandatory schema change for the gsql database backends. See files named 4.3.x_to_4.7.0_schema.X.sql for your database backend in our Git repo, tarball, or distro-specific documentation path. For the LMDB backend, please review [lmdb-schema-version](https://doc.powerdns.com/authoritative/backends/lmdb.html#setting-lmdb-schema-version). The new LMDB schema version is 4.

*Which now makes absolute sense that I receive the error, as it is obviously missing in my "old" database.*

I found the necessary schema upgrades [here](https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/4.3.0_to_4.7.0_schema.mysql.sql):

```sql
ALTER TABLE domains ADD options VARCHAR(64000) DEFAULT NULL;
ALTER TABLE domains ADD catalog VARCHAR(255) DEFAULT NULL;
ALTER TABLE domains MODIFY type VARCHAR(8) NOT NULL;

CREATE INDEX catalog_idx ON domains(catalog);
```

I punched these into the database, recreated the container and now it works.

I wonder why the slave never had any issues. I created the columns there too, doesn't seem to have any kind of impact.

---
Maybe this helps somebody, if something unforeseen would happen I would update the issue, but I think it can be closed.

**Comment by pschiffe** [comment]
Thank you for the investigation, the migration has been now included in the startup script.
