### ISSUE TITLE
Deploying Authoritative and Recursive DNS on the same VM with Master-Slave capabillity

### ISSUE THREAD

**Issue by ijonjic11** [pschiffe/docker-pdns#99]
Hi @pschiffe, i want to deploy pdns in docker with master-slave feature. Authoritative and Recursive DNS need to be on the same  VM.

Infrastructure details:
VM1 (pdns-master): Rocky Linux 8.7 - 10.x.x.110
VM2 (pdns-slave): Rocky Linux 8.7 - 10.x.x.210

Can you provide me docker-compose.yml file for deploy PDNS in this way or can you help me with writing it.

I was trying do it alone,using your resources and few other, but with no  success.

Thank you in advance.

**Comment by pschiffe** [comment]
Hi @ijonjic11 , you can start by adjusting the docker compose from this repo - https://github.com/pschiffe/docker-pdns/blob/master/docker-compose.yml
However, note that if you want to expose the dns services outside of the vm, authoritative and recursive servers shares the same ports by default (53 tcp and udp). If you need them on the same VM, I suggest you to assign second IP to the first VM, so one IP is used by the authoritative server and one by the recursive one.

**Comment by ijonjic11** [comment]
Hi @pschiffe, I've assigned second IP to the first VM. Now i have setup like this:

Infrastructure details:
VM1 (pdns-master): Rocky Linux 8.7 - 10.x.x.110, 10.x.x.111
VM2 (pdns-slave): Rocky Linux 8.7 - 10.x.x.210

I tryed to run docker-compose file on the first VM using following config:

version: '2.4'

services:

  pdns-recursor:
    image: pschiffe/pdns-recursor:${RECURSOR_TAG:-latest}
    networks:
      - pdns
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mariadb:
    image: mariadb:10.10
    networks:
      pdns:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5
    networks:
      - pdns
    ports:
      - '8988:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro

  pdns-master:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: pdns-master.internal.company.com
    networks:
      pdns:
        ipv4_address: 10.x.x.110
        aliases:
          - pdns
    extra_hosts:
      - 'pdns-master.internal.company.com:10.x.x.110'
      - 'pdns-slave.internal.company.com:10.x.x.210'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gmysql_password=password123
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=172.6.0.0/16,10.x.x.0/24
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=10.x.x.210
      - PDNS_only_notify=10.x.x.210
    depends_on:
      - mariadb


  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi
    networks:
      pdns:
        aliases:
          - pdns-admin-uwsgi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_PASSWORD='password123'
      - PDNS_VERSION=4.7
      - PDNS_API_KEY=secret
    depends_on:
      - mariadb
      - pdns-master

  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    networks:
      - pdns
    ports:
      - '8989:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pdns-admin-uwsgi

networks:
  pdns:
    ipam:
      config:
        - subnet: 10.x.x.0/24
          gateway: 10.x.x.1



**************************************************
I suppose that pdns-slave part need to be included on the second VM. I want to make sure that master side is working for the start and then i will deal with slave side.

After i run docker-compose up -d, i'm getting this:
service "mariadb" refers to undefined volume mariadb: invalid compose project

Can you check please is there any typo in the file or do i need to do additional configuration before running compose file.

Also,i have one more question:

Does pdns-master service include both, authoritative and recursive servers or do i need to deploy recursive server separately as container?

Thank you!

**Comment by pschiffe** [comment]
> After i run docker-compose up -d, i'm getting this:
> service "mariadb" refers to undefined volume mariadb: invalid compose project
> There is a typo in the line:
> 
>     mariadb:/var/lib/mysql:z
>     It needs to be like this i suppose:
>     /mariadb:/var/lib/mysql:z

`mariadb:/var/lib/mysql:z` is correct, but you are missing [volume definition](https://github.com/pschiffe/docker-pdns/blob/master/docker-compose.yml#L127) in the docker compose.

> When i try to create new domain via GUI (10.x.x.110:8989), i'am getting 400 Bad Request.

Could you post logs from `pdns-admin-uwsgi`, `pdns-admin-static` and `pdns-master` after the error happens?

I also see the networking is not correct, docker is using it's own network layer, that shouldn't be mixed with the vm network. The network definition can stay as in the original repo:
```
networks:
  pdns:
    ipam:
      config:
        - subnet: 172.6.0.0/16
          gateway: 172.6.0.1
```
The IPs of the containers can be assigned dynamically, that's not a problem in this case I think, just bind the ports to the correct external IPs:
```
...
pdns-recursor:
  image: pschiffe/pdns-recursor:${RECURSOR_TAG:-latest}
  networks:
    - pdns
  ports:
    - '10.x.x.111:53:53/tcp'
    - '10.x.x.111:53:53/udp'
  volumes:
    - /etc/localtime:/etc/localtime:ro
...
pdns-master:
  image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
  hostname: pdns-master.internal.company.com
  networks:
    pdns:
      aliases:
        - pdns
  ports:
    - '10.x.x.110:53:53/tcp'
    - '10.x.x.110:53:53/udp'
...
```

**Comment by ijonjic11** [comment]
Hi,i've done all the changes from the above and now i can create domains. How can i test if recursive DNS is returning answers. I tried with "dig" on my local PC but it is not working. Before that i added "nameserver 10.x.x.111" in /etc/resolv.conf file.


Also I've created domain "internal.company.com" and added A and PTR for the first VM, like this:

![Screenshot from 2023-02-16 14-49-48](https://user-images.githubusercontent.com/60158133/219383438-10c1b9a6-34ed-4c5c-8363-3b23f2a08c94.png)

Is there something that i'm missing here?

**Comment by pschiffe** [comment]
With `dig`, you can select the nameserver directly, here I'm asking DNS server on address `1.1.1.1`:
```
dig @1.1.1.1 google.com
```
So you can test your resolver with `dig @10.x.x.111 google.com`. First, try to make it work for public records, like google.com. If it doesn't work, check logs from the resolver. Then, try to make work your own records. You probably will need to add extra config to the resolver for your own domains on your own authoritative dns server with [forward-zones](https://docs.powerdns.com/recursor/settings.html#forward-zones) option.

**Comment by ijonjic11** [comment]
Okay,thank you. After adding forward zones,it works for Public and Private Records (Tested on forward and reverse requests).

Now i need help with setting up slave VM. What parts needs to be in docker-compose.yml file for slave configuration? I suppose that i need to leave pdns-slave service and delete pdns-master service, everything else rest the same,right?

**Comment by ijonjic11** [comment]
Hi @pschiffe , i've manage to deploy slave server and replication is working for adding,editing and removing records. When i delete entire domain from master,deletion is not done on slave. Is there a way to accomplish that. If not,it's not a big deal since domain removing is not an every day operation so i can manually delete it using phpmyadmin.

Also, is it possible to add persistent volumes for containers and make sure that they are started after boot of VM etc. (for example "restart: always")

**Comment by pschiffe** [comment]
Hello. Slaves currently don't auto delete zones removed on master. There are scripts like this [one](https://github.com/verdel/powerdns-slave-cleaner), but yeah, depending on the scale, you may handle it manually.

If you are using docker and docker-compose, containers should automatically start after a reboot, unless explicitly stopped via docker or docker-compose command. But of course you can add the `restart: always` [param](https://docs.docker.com/compose/compose-file/#restart) to all containers that should be automatically restarted by docker if they are unexpectedly stopped.

For persistency, I think only mysql needs a named volume, as shown [here](https://github.com/pschiffe/docker-pdns/blob/master/docker-compose.yml#L21).

**Comment by ijonjic11** [comment]
Okay,thanks,i've manage to config it and its working as expected. Just for info,is it possible to run recursor and authoritative server on same IP but on different port ( Auth=5300, Recursor=53). I've tried it already and its working but after that replication is not working. 
Output of "docker logs root-pdns-slave-1" command looks like this:

Feb 20 11:17:20 XFR-in zone: 'internal.company.com', primary: '10.x.x.110', unable to xfr zone (ResolverException): AXFR chunk error: Server Failure (This was attempt number 1. Excluding zone from slave-checks until 1676888300)

**Comment by pschiffe** [comment]
> I've tried it already and its working but after that replication is not working.

That was my point, so the replication is working, and the configuration is simpler in general :-)

But I think yes, you can have them both on the same IP with different ports, you just need to configure the master's port in slave configuration, so it knows where to find it. As well as the [forward-zones](https://docs.powerdns.com/recursor/settings.html#forward-zones) on recursor where you can specify the port of the master.

Not sure though exactly about the required configuration change for the slave. It depends on how exactly you configured the replication. If you used `SUPERMASTER_IPS` feature, try to take a look [here](https://doc.powerdns.com/authoritative/modes-of-operation.html#supermaster-operation). Maybe updating some tables in mysql can fix it.
